apiVersion: batch/v1
kind: Job
metadata:
  name: cert-service
spec:
  # https://kubernetes.io/docs/concepts/jobs/run-to-completion-finite-workloads/#job-termination-and-cleanup
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: cert-loader
    spec:
      # this creates a temporary container just to run this Job
      containers:
      - name: cert-loader
        image: gcr.io/jwnwilson-eu/nginx:v1
        command: ["certbot certonly -n -m jwnwilson@gmail.com --agree-tos -d noel-wilson.co.uk && openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048"]
        env:
        - name: SERVER_HOST
          value: server
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/letsencrypt/live
          name: ssl-volume
      volumes:
      - name: secret-volume
      - name: ssl-volume
      restartPolicy: OnFailure
