apiVersion: batch/v1
kind: Job
metadata:
  name: db-service
spec:
  # https://kubernetes.io/docs/concepts/jobs/run-to-completion-finite-workloads/#job-termination-and-cleanup
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: mongo-data-loader
    spec:
      # this creates a temporary container just to run this Job
      containers:
      - name: mongo-data-loader
        image: gcr.io/jwnwilson-eu/db:v1
        command: ["/reset_db.sh"]
        env:
        - name: DB_URI
          value: mongodb://db:27017
        - name: DB_HOST
          value: db
      restartPolicy: OnFailure
